debug: true

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG

spring:
  application:
    name: booking-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate

aws:
  region: us-east-1
  s3:
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
    endpoint: ${MINIO_ENDPOINT}
    path-style-access-enabled: true

  buckets:
    movie-service: "movie-images"
