logging:
  level:
    root: INFO
    #org.flywaydb: DEBUG

spring:
  application:
    name: booking-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 60000

aws:
  region: us-east-1
  s3:
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
    endpoint: ${MINIO_ENDPOINT}
    path-style-access-enabled: true

  buckets:
    movie-service: "movie-images"

jwt:
  secret:
    access: ${ACCESS_TOKEN_SECRET}
    refresh: ${REFRESH_TOKEN_SECRET}
  ttl:
    refresh: 30